회원 도메인 개선
YAPP-Github/21st-ALL-Rounder-Team-2-BE pull request #119
Opened 2023-03-29 19:44 UTC by le2sky

# 구현 내용

## 구현 요약

회원 도메인에 헥사고날 적용 중. 지옥문 열렸다

## 관련 이슈

#118 

## 구현 내용

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/common/BaseControllerIntegrationTest.java
> +public abstract class BaseControllerIntegrationTest {
[PTAL] 컨트롤러에 통합테스트를 할때, 중복되는 설정이나 시큐리티 설정을 abstract로 추상화 해놨어요! 상속받는 통합 테스트에서는 

```
@Test
void test(){
    givenUserByReference(UserTestData.defaultUser().build());
}
```  
를 사용하면, 컨트롤러에서 원하는 authentication 객체를 받을 수 있어요!

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/common/UserTestData.java
> +public class UserTestData {
[PTAL] 유저에 대한 테스트 데이터 클래스입니다!

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetUserControllerTest.java
> +class GetUserControllerTest extends BaseControllerIntegrationTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetUserThumbnailControllerTest.java
> +class GetUserThumbnailControllerTest extends BaseControllerIntegrationTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/adapter/in/web/RegisterUserControllerTest.java
> +class RegisterUserControllerTest extends BaseControllerIntegrationTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/adapter/in/web/UserWithdrawalControllerTest.java
> +class UserWithdrawalControllerTest extends BaseControllerIntegrationTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/adapter/in/web/RenameUserControllerTest.java
> +class RenameUserControllerTest extends BaseControllerIntegrationTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/adapter/out/authentication/FirebaseAuthenticationAdapterTest.java
> +class FirebaseAuthenticationAdapterTest {
[PTAL] 인증 어댑터 같은 경우에는 통합테스트가 아닌, 단위 테스트를 작성했습니다. 스프링 프레임워크에 종속되어 무언갈 한다기 보다는 외부 라이브러리에 의존하기 때문에 그런 판단을 했습니다!

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/adapter/out/authentication/FirebaseUserRemoverTest.java
> +class FirebaseUserRemoverTest {
[PTAL] 여기서 모킹하기 위해서 AbstractFirebaseAuth를 사용하도록 변경했습니다

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/adapter/out/authentication/JwtDecoderTest.java
> +class JwtDecoderTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/adapter/out/persistence/UserPersistenceAdapterTest.java
> +class UserPersistenceAdapterTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/application/service/GetUserDetailsServiceTest.java
> +class GetUserDetailsServiceTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/application/service/GetUserServiceTest.java
> +class GetUserServiceTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/application/service/GetUserThumbnailServiceTest.java
> +class GetUserThumbnailServiceTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/application/service/RegisterUserServiceTest.java
> +class RegisterUserServiceTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/application/service/RenameUserServiceTest.java
> +class RenameUserServiceTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/application/service/UserWithdrawalServiceTest.java
> +class UserWithdrawalServiceTest {
[PTAL]

2023-04-04 11:13 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/domain/UserTest.java
> +class UserTest {
[PTAL] 내부에 있던 `TEST_SAVED_USER`은 유일하게 사용하는 테스트 클래스 내부로 위치 시켰습니다!

2023-04-04 11:13 UTC, le2sky commented on src/test/resources/application.yml
> +        format_sql: true
[PTAL] 쿼리 개선할때 필요해서 ` format_sql` 옵션 true로 변경했어요!

2023-04-04 11:13 UTC, le2sky commented on src/test/resources/com/yapp/artie/domain/user/adapter/out/persistence/UserPersistenceAdapterTest.sql
> +INSERT INTO `user`
[PTAL] 다음과 같이 SQL 파일을 따로 분리했어요. persistence adapter를 통합 테스트할 때,  이런 방식으로 외부 환경을 세팅하면 편리하다고 느꼈어요!

2023-04-04 11:14 UTC, le2sky reviewed
ㅊ

2023-04-14 16:46 UTC, akalswl14 reviewed
일정으로 인해 리뷰가 늦어진 점을 양해주셔서 감사합니다!!

아직 모든 코드를 확인하진 못했지만, 첨부한 블로그 글 2번째까지의 분량을 확인하였습니다.
현재 시점에서, 두 가지 이야기할 사항이 있습니다.

1. UID에 대한 인덱스 설정
UID에 인덱스를 설정한 것은 옳은 선택이라고 생각합니다. ( 우리 이거 논의했었나요?? 왜 익숙한지 모르겠어요 ㅋㅋㅋㅋㅋ ) 
그리고, varchar(255)로 인해 인덱스로 부여하는 것이 DB에 부담이 될 수 있다는 점도 이해합니다!
제가 Firebase UID 속성을 찾아보니까 1~128자의 문자열이라고 하네요!
아직 QA 과정 중에 있으니, varchar 크기를 줄이는 건 어떤가요?
https://firebase.google.com/docs/auth/admin/manage-users?hl=ko#bulk_retrieve_user_data
위 URL의 "표 1. 사용자 생성 작업에서 지원하는 속성" 을 확인해보세요!
다만, 카카오, 네이버 처럼 서드 파티 소셜 로그인 공급자에 대해서 특별히 UID 길이가 관련있는 것 같지는 않지만, 혹시 관련되서 이슈가 있다면 말씀해주세요!

2. 도메인 모델과 영속성 분리로 인한 레포지토리 메소드 중복 호출
RenameUserService의 rename 메소드에서 loadById와 updateName을 사용하고 있습니다.
두 메소드는 둘다, findByUidOrElseThrow를 호출하고 있고, 이  findByUidOrElseThrow 메소드는 UserRepository.findByUid를 호출해 동일한 요청이 중복되어 수행됩니다.
1차 캐시에서 해당 User 데이터를 가지고 있으니까 상관없을까요? 상관없을 것으로 생각되나, 가령 상관없다고 하더라도 이러한 접근이 맞는 것인지, 1차 캐시에서 데이터를 가지고 있는지 확인해봐야겠네요(저도 해볼게요)

천천히 답변주세요, 수고하셨습니다!!!!! 💯💯💯💯

2023-04-17 00:05 UTC, akalswl14 commented on src/main/java/com/yapp/artie/domain/user/application/service/UserNotFoundException.java
> +public class UserNotFoundException extends BusinessException {
저는 예외가 도메인 패키지에 위치해야한다고 생각해요!

우선, 예외가 아주 다양하게 구성되어 있지 않기 때문에 서비스 예외와 도메인 예외를 분리시킬 수준은 아직 아니라고 생각합니다.
하지만 유저 도메인의 예외는 도메인 예외에 가깝다고 생각되어, domain에 위치하는게 좋지 않을까 생각했습니다.

2023-04-17 07:52 UTC, akalswl14 requested changes

2023-04-17 07:52 UTC, akalswl14 commented on src/main/java/com/yapp/artie/global/deprecated/LoadUserJpaEntityApi.java
> +public interface LoadUserJpaEntityApi {
외부에서 유저에 대한 의존성이 없도록 global 패키지에 넣은 것이고,
하지만 로직은 유저 JPA 엔티티에 의존하고 있는 것이라 최종적으로는 의존성이 있다.
맞나요?
Category.ownerId부분을 이해하지 못했는데, 외래키로써 저장하지 말자는 뜻일까요?

2023-04-17 07:52 UTC, akalswl14 commented on src/main/java/com/yapp/artie/global/deprecated/UserJpaEntityLoader.java
> +  private final EntityManager em;
JPA 수준까지는 필요 없으니까 em을 호출했다. 맞을까요???

2023-04-17 07:52 UTC, akalswl14 commented on src/test/java/com/yapp/artie/domain/user/application/service/UserWithdrawalServiceTest.java
> +  }
givenUser, givenUserFindWillFail 등의 유저를 load 하여 모킹하는 메소드가 중복적으로 많이 나타나는 것 같은데, test.User.common 내에 abtract class test로 구성하는건 어떻게 생각하시나요??

2023-04-17 07:55 UTC, akalswl14 commented
모든 코드에 대한 리뷰를 마쳤습니다! 일부 답변을 단 부분이 있으니 확인 부탁드려요!

2023-04-18 14:06 UTC, le2sky commented on src/main/java/com/yapp/artie/domain/user/adapter/in/web/RenameUserController.java
> +    System.out.println(authentication);
헉 이 부분 제대로 확인을 못했었네요 감사합니다! 수정해둘게요

2023-04-18 14:13 UTC, le2sky commented on src/main/java/com/yapp/artie/domain/user/application/service/UserNotFoundException.java
> +public class UserNotFoundException extends BusinessException {
`서비스 예외와 도메인 예외를 분리시킬 수준은 아직 아니라고 생각합니다.` 이 부분에 저도 동의합니다! 
 그리고 이건 민지님의 의견을 좀 더 뒷받침할 수 있다고 생각이 드는데요. 리포지터리에서 나오는 예외 = 도메인 예외 이렇게 생각이 들기도 하네요. (DDD에서는 리포지터리가 도메인 레이어의 구성요소라고 하네요!) 이 부분도 반영해둘게요!

2023-04-18 14:22 UTC, le2sky commented on src/main/java/com/yapp/artie/global/deprecated/LoadUserJpaEntityApi.java
> +public interface LoadUserJpaEntityApi {
넵 이해하신게 맞습니다!  `Category.ownerId부분을 이해하지 못했는데, 외래키로써 저장하지 말자는 뜻일까요?` 이부분은 Category 엔티티에서 외래키 제약을 검사하기 위해서 UserJpaEntity를 합성 관계로 가지고 있는데요. 차라리 User(도메인 엔티티)를 가지고 있거나, Long 타입의 회원 ID를 가지고 있거나, 아예 값 타입으로 MemberId를 가지고 있는 것이 의존성의 관점에서는 훨씬 낫다고 생각했어요! 

그리고 이건 추측인데, 굳이 UserJpaEntity를 안가지고 Long만 있어도 OR 매핑은 잘 수행될 것 같은 느낌이 들기도 하네요! (전시 도메인에서는 도메인 엔티티와 영속성 엔티티를 매핑 안한다고 했을 때!)

2023-04-18 14:23 UTC, le2sky commented on src/main/java/com/yapp/artie/global/deprecated/UserJpaEntityLoader.java
> +  private final EntityManager em;
넵 의존성을 최소화하려고, Persistence Adapter나 Repository 대신 em을 사용했어요!

2023-04-18 14:23 UTC, le2sky commented on src/test/java/com/yapp/artie/domain/user/application/service/UserWithdrawalServiceTest.java
> +  }
이부분은 생각치도 못했는데 좋은 아이디어네요! 반영 해보겠습니다!

2023-04-18 14:29 UTC, le2sky reviewed
커밋 추가된 거 확인했습니다!

2023-04-19 07:55 UTC, akalswl14 approved these changes
LGTM 👍

2023-04-19 08:05 UTC, merged